### ISSUE TITLE
How can I make TravisCI work on your book?

### ISSUE THREAD

**Issue by Rindrics** [siddhi/test_driven_python#2]
Thank you for writing great book!

Would you tell me how can I set TravisCI to run tests of this repo.

I'm using setting below but Travis does not work:
```yml
language: python
python: 3.7
script:
  - python -m unittest discover
```

Thank you!
